const leaderBoardData = [
  {
    rank: 1,
    name: "DEEPALAKSHMI RAVICHANDREN",
    batch: "B52 WE TAMIL",
    learning: "80.56",
  },
  {
    rank: 2,
    name: "Leo nimalraj",
    batch: "B52 WE TAMIL",
    learning: "78.06",
  },
  {
    rank: 3,
    name: "Thamarai kannan",
    batch: "B52 WE TAMIL",
    learning: "57.31",
  },
  {
    rank: 4,
    name: "Rakshana",
    batch: "B52 WE TAMIL",
    learning: "51.30",
  },
  {
    rank: 5,
    name: "Aravinthan B",
    batch: "B52 WE TAMIL",
    learning: "49.63",
  },
  {
    rank: 6,
    name: "MOHANA PRIYA M K",
    batch: "B52 WE TAMIL",
    learning: "47.41",
  },
  {
    rank: 7,
    name: "Valliyappan",
    batch: "B52 WE TAMIL",
    learning: "46.85",
  },
  {
    rank: 8,
    name: "Alfina M",
    batch: "B52 WE TAMIL",
    learning: "42.96",
  },
  {
    rank: 9,
    name: "Selvam G",
    batch: "B52 WE TAMIL",
    learning: "37.69",
  },
  {
    rank: 10,
    name: "DGuna",
    batch: "B52 WE TAMIL",
    learning: "37.31",
  },
  {
    rank: 11,
    name: "S.L.NANDHANA",
    batch: "B52 WE TAMIL",
    learning: "35.00",
  },
  {
    rank: 12,
    name: "Jayachandren K",
    batch: "B52 WE TAMIL",
    learning: "30.74",
  },
  {
    rank: 13,
    name: "Hithesh J M",
    batch: "B52 WE TAMIL",
    learning: "29.63",
  },
  {
    rank: 14,
    name: "Suriya R",
    batch: "B52 WE TAMIL",
    learning: "25.74",
  },
  {
    rank: 15,
    name: "Gawasker ",
    batch: "B52 WE TAMIL",
    learning: "24.63",
  },
  {
    rank: 16,
    name: "Vidhya Dayalan",
    batch: "B52 WE TAMIL",
    learning: "23.33",
  },
  {
    rank: 17,
    name: "Sasikumar S",
    batch: "B52 WE TAMIL",
    learning: "19.81",
  },
  {
    rank: 18,
    name: "Yogeshwari",
    batch: "B52 WE TAMIL",
    learning: "18.89",
  },
  {
    rank: 19,
    name: "adya varshini",
    batch: "B52 WE TAMIL",
    learning: "16.70",
  },
  {
    rank: 20,
    name: "Bhuvaneshwari j",
    batch: "B52 WE TAMIL",
    learning: "14.26",
  },
  {
    rank: 21,
    name: "Vinith",
    batch: "B52 WE TAMIL",
    learning: "12.41",
  },
  {
    rank: 22,
    name: "Selva pandi",
    batch: "B52 WE TAMIL",
    learning: "12.13",
  },
  {
    rank: 23,
    name: "Kannan S",
    batch: "B52 WE TAMIL",
    learning: "11.85",
  },
  {
    rank: 24,
    name: "Chitra S",
    batch: "B52 WE TAMIL",
    learning: "11.67",
  },
  {
    rank: 25,
    name: "Aravinthan M",
    batch: "B52 WE TAMIL",
    learning: "8.33",
  },
  {
    rank: 26,
    name: "julious",
    batch: "B52 WE TAMIL",
    learning: "6.30",
  },
  {
    rank: 27,
    name: "Thilack Banu Panneer Selvam",
    batch: "B52 WE TAMIL",
    learning: "5.93",
  },
  {
    rank: 28,
    name: "Barveen Babi Raja Mohammed",
    batch: "B52 WE TAMIL",
    learning: "5.93",
  },
  {
    rank: 29,
    name: "Thilogithan Thangaraja",
    batch: "B52 WE TAMIL",
    learning: "5.56",
  },
  {
    rank: 30,
    name: "TENMOZHI RATHNA J",
    batch: "B52 WE TAMIL",
    learning: "5.19",
  },
  {
    rank: 31,
    name: "Harikrishnan D",
    batch: "B52 WE TAMIL",
    learning: "2.22",
  },
];

export default leaderBoardData;
